## Vectorization

### One-Hot Encoding

In [1]:
Corpos = ["dog eats meats man", "man eats meat"]
vocab = {}
count = 0
for doc in Corpos:
    for word in doc.split():
        if word not in vocab:
            count = count+1
            vocab[word] = count -1
print(vocab)

{'dog': 0, 'eats': 1, 'meats': 2, 'man': 3, 'meat': 4}


In [2]:
def one_hot_encodding(doc):
    one_hot = []
    for word in doc.split():
        # print(word)
        temp = [0]*len(vocab)
        if word in vocab:
            print(vocab[word])
            temp[vocab[word]] =1
        one_hot.append(temp)
    return one_hot

In [3]:
one_hot_encodding("dog eats meat")

0
1
4


[[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 1]]

## Bag of words

In [4]:
# import pandas as pd
import numpy as np
import collections

In [5]:
doc1 = "Harry potter is an amzaing movie"
doc2 = "Harry potter is the best movie"
doc3 = "Harry potter is so great"


In [6]:
import re
doc1 = re.sub(r"[^a-zA-z0-9]"," ", doc1.lower()).split()
print(doc1)
doc2 = re.sub(r"[^a-zA-z0-9]"," ", doc2.lower()).split()
print(doc2)
doc3 = re.sub(r"[^a-zA-z0-9]"," ", doc3.lower()).split()
print(doc3)

['harry', 'potter', 'is', 'an', 'amzaing', 'movie']
['harry', 'potter', 'is', 'the', 'best', 'movie']
['harry', 'potter', 'is', 'so', 'great']


In [7]:
all_words = set(doc1+doc2+doc3) ## Unique words we got from text corpous
print(all_words), type(all_words)

{'potter', 'so', 'harry', 'best', 'amzaing', 'is', 'an', 'the', 'movie', 'great'}


(None, set)

In [8]:
dict.fromkeys(all_words,1)

{'potter': 1,
 'so': 1,
 'harry': 1,
 'best': 1,
 'amzaing': 1,
 'is': 1,
 'an': 1,
 'the': 1,
 'movie': 1,
 'great': 1}

In [9]:
doc1.count("potter")

1

In [10]:
def BowRepresentation(all_uniquewords, documents):
    bow = dict.fromkeys(all_uniquewords,0)
    for word in documents:
        bow[word] = doc1.count(word)

    return bow

In [11]:
doc_1 = BowRepresentation(all_words,doc1)
doc_2 = BowRepresentation(all_words,doc2)
doc_3 = BowRepresentation(all_words,doc3)
print(doc_1, doc1), print(doc_2,doc2), print(doc_3, doc3)

{'potter': 1, 'so': 0, 'harry': 1, 'best': 0, 'amzaing': 1, 'is': 1, 'an': 1, 'the': 0, 'movie': 1, 'great': 0} ['harry', 'potter', 'is', 'an', 'amzaing', 'movie']
{'potter': 1, 'so': 0, 'harry': 1, 'best': 0, 'amzaing': 0, 'is': 1, 'an': 0, 'the': 0, 'movie': 1, 'great': 0} ['harry', 'potter', 'is', 'the', 'best', 'movie']
{'potter': 1, 'so': 0, 'harry': 1, 'best': 0, 'amzaing': 0, 'is': 1, 'an': 0, 'the': 0, 'movie': 0, 'great': 0} ['harry', 'potter', 'is', 'so', 'great']


(None, None, None)

In [12]:
import pandas as pd

In [13]:
dataframe = pd.DataFrame([doc_1, doc_2, doc_3])
dataframe

potter  so  harry  best  amzaing  is  an  the  movie  great
0       1   0      1     0        1   1   1    0      1      0
1       1   0      1     0        0   1   0    0      1      0
2       1   0      1     0        0   1   0    0      0      0

In [14]:
doc1

['harry', 'potter', 'is', 'an', 'amzaing', 'movie']

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(binary=True)
doc1 = "Harry potter is an amzaing movie"
doc2 = "Harry potter is the best movie"
doc3 = "Harry potter is so great"

cv_out = cv.fit_transform([doc1,doc2,doc3])
print(cv_out.toarray()), print(cv.get_feature_names_out())

[[1 1 0 0 1 1 1 1 0 0]
 [0 0 1 0 1 1 1 1 0 1]
 [0 0 0 1 1 1 0 1 1 0]]
['amzaing' 'an' 'best' 'great' 'harry' 'is' 'movie' 'potter' 'so' 'the']


(None, None)

In [16]:
dataFRAME = pd.DataFrame(cv_out.toarray(), columns=cv.get_feature_names_out())
dataFRAME

amzaing  an  best  great  harry  is  movie  potter  so  the
0        1   1     0      0      1   1      1       1   0    0
1        0   0     1      0      1   1      1       1   0    1
2        0   0     0      1      1   1      0       1   1    0

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,3)) ## Unigram, Biagram, Trigram
doc1 = "Harry potter is an amzaing movie"
doc2 = "Harry potter is the best movie"
doc3 = "Harry potter is so great"

cv_out = cv.fit_transform([doc1,doc2,doc3])
print(cv_out.toarray()), print(cv.get_feature_names_out())

[[1 1 1 1 1 0 0 0 1 1 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1 0 0 1 1 1]
 [0 0 0 0 0 0 0 1 1 1 1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 0 0 0]]
['amzaing' 'amzaing movie' 'an' 'an amzaing' 'an amzaing movie' 'best'
 'best movie' 'great' 'harry' 'harry potter' 'harry potter is' 'is'
 'is an' 'is an amzaing' 'is so' 'is so great' 'is the' 'is the best'
 'movie' 'potter' 'potter is' 'potter is an' 'potter is so'
 'potter is the' 'so' 'so great' 'the' 'the best' 'the best movie']


(None, None)

In [18]:
dataFRAME = pd.DataFrame(cv_out.toarray(), columns=cv.get_feature_names_out())
dataFRAME

amzaing  amzaing movie  an  an amzaing  an amzaing movie  best  best movie  \
0        1              1   1           1                 1     0           0   
1        0              0   0           0                 0     1           1   
2        0              0   0           0                 0     0           0   

   great  harry  harry potter  ...  potter  potter is  potter is an  \
0      0      1             1  ...       1          1             1   
1      0      1             1  ...       1          1             0   
2      1      1             1  ...       1          1             0   

   potter is so  potter is the  so  so great  the  the best  the best movie  
0             0              0   0         0    0         0               0  
1             0              1   0         0    1         1               1  
2             1              0   1         1    0         0               0  

[3 rows x 29 columns]

## TF-IDF

In [19]:
import pandas as pd
import math
import sklearn

In [20]:
first_sentence = "Data science is an Amazing career in the current world"
second_sentence = "Deep learning is a subset of machine learning"

first_sen_tokens = first_sentence.split(" ")
second_sen_tokens = second_sentence.split(" ")
print(first_sen_tokens), print(second_sen_tokens)
vacabulary = set(first_sen_tokens).union(set(second_sen_tokens))
vacabulary

['Data', 'science', 'is', 'an', 'Amazing', 'career', 'in', 'the', 'current', 'world']
['Deep', 'learning', 'is', 'a', 'subset', 'of', 'machine', 'learning']


{'Amazing',
 'Data',
 'Deep',
 'a',
 'an',
 'career',
 'current',
 'in',
 'is',
 'learning',
 'machine',
 'of',
 'science',
 'subset',
 'the',
 'world'}

In [21]:
dict_1 = dict.fromkeys(vacabulary, 0)
dict_2 = dict.fromkeys(vacabulary, 0)

for word in first_sen_tokens:
    dict_1[word] +=1

for word in second_sen_tokens:
    dict_2[word] +=1

print(dict_1), print(dict_2)

{'current': 1, 'in': 1, 'Deep': 0, 'Amazing': 1, 'world': 1, 'a': 0, 'Data': 1, 'of': 0, 'is': 1, 'an': 1, 'career': 1, 'the': 1, 'machine': 0, 'subset': 0, 'science': 1, 'learning': 0}
{'current': 0, 'in': 0, 'Deep': 1, 'Amazing': 0, 'world': 0, 'a': 1, 'Data': 0, 'of': 1, 'is': 1, 'an': 0, 'career': 0, 'the': 0, 'machine': 1, 'subset': 1, 'science': 0, 'learning': 2}


(None, None)

In [22]:
df = pd.DataFrame([dict_1, dict_2])
df

current  in  Deep  Amazing  world  a  Data  of  is  an  career  the  \
0        1   1     0        1      1  0     1   0   1   1       1    1   
1        0   0     1        0      0  1     0   1   1   0       0    0   

   machine  subset  science  learning  
0        0       0        1         0  
1        1       1        0         2

In [23]:
## tf = freq of a word in a document / total number of words in a document
def calculateTF(wordDict, doc):
    tfdict = {}
    len_corpos = len(doc)

    for word, count in wordDict.items():
        tfdict[word] = count/len_corpos
    return tfdict

tf_sen_1 = calculateTF(dict_1, first_sen_tokens)
tf_sen_2 = calculateTF(dict_2, second_sen_tokens)

print(tf_sen_1), print(tf_sen_2)

{'current': 0.1, 'in': 0.1, 'Deep': 0.0, 'Amazing': 0.1, 'world': 0.1, 'a': 0.0, 'Data': 0.1, 'of': 0.0, 'is': 0.1, 'an': 0.1, 'career': 0.1, 'the': 0.1, 'machine': 0.0, 'subset': 0.0, 'science': 0.1, 'learning': 0.0}
{'current': 0.0, 'in': 0.0, 'Deep': 0.125, 'Amazing': 0.0, 'world': 0.0, 'a': 0.125, 'Data': 0.0, 'of': 0.125, 'is': 0.125, 'an': 0.0, 'career': 0.0, 'the': 0.0, 'machine': 0.125, 'subset': 0.125, 'science': 0.0, 'learning': 0.25}


(None, None)

In [24]:
tf_dataframe = pd.DataFrame([tf_sen_1, tf_sen_2])
tf_dataframe

current   in   Deep  Amazing  world      a  Data     of     is   an  \
0      0.1  0.1  0.000      0.1    0.1  0.000   0.1  0.000  0.100  0.1   
1      0.0  0.0  0.125      0.0    0.0  0.125   0.0  0.125  0.125  0.0   

   career  the  machine  subset  science  learning  
0     0.1  0.1    0.000   0.000      0.1      0.00  
1     0.0  0.0    0.125   0.125      0.0      0.25

In [25]:
import nltk
from nltk.corpus import stopwords
all_stop_words = stopwords.words("english")

In [26]:
f1 = [word for word in first_sen_tokens if word not in all_stop_words]
f2 = [word for word in second_sen_tokens if word not in all_stop_words]
f1, f2

(['Data', 'science', 'Amazing', 'career', 'current', 'world'],
 ['Deep', 'learning', 'subset', 'machine', 'learning'])

In [27]:
def calculateIDF(doc):
    idfDict = {}
    len_doc = len(doc)

    idfDict = dict.fromkeys(doc[0],0)
    for word, val in idfDict.items():
        idfDict[word] = math.log10(len_doc/(float(val)+1))

    return idfDict


In [28]:
idf = calculateIDF([dict_1 ,dict_2])
idf

{'current': 0.3010299956639812,
 'in': 0.3010299956639812,
 'Deep': 0.3010299956639812,
 'Amazing': 0.3010299956639812,
 'world': 0.3010299956639812,
 'a': 0.3010299956639812,
 'Data': 0.3010299956639812,
 'of': 0.3010299956639812,
 'is': 0.3010299956639812,
 'an': 0.3010299956639812,
 'career': 0.3010299956639812,
 'the': 0.3010299956639812,
 'machine': 0.3010299956639812,
 'subset': 0.3010299956639812,
 'science': 0.3010299956639812,
 'learning': 0.3010299956639812}

In [29]:
def computeTFIDF(tfBow, idfs):
    tfidf = {}
    for word, val in tfBow.items():
       tfidf[word] = val* idfs[word]

    return tfidf 

In [30]:
idf1 = computeTFIDF(tf_sen_1, idf)
idf2 = computeTFIDF(tf_sen_2, idf)

In [31]:
tfidf_df = pd.DataFrame([idf1, idf2])
tfidf_df

current        in      Deep   Amazing     world         a      Data  \
0  0.030103  0.030103  0.000000  0.030103  0.030103  0.000000  0.030103   
1  0.000000  0.000000  0.037629  0.000000  0.000000  0.037629  0.000000   

         of        is        an    career       the   machine    subset  \
0  0.000000  0.030103  0.030103  0.030103  0.030103  0.000000  0.000000   
1  0.037629  0.037629  0.000000  0.000000  0.000000  0.037629  0.037629   

    science  learning  
0  0.030103  0.000000  
1  0.000000  0.075257

### From Sklearn 

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
vec =  TfidfVectorizer()
result = vec.fit_transform([first_sentence, second_sentence])
result.toarray()

array([[0.32433627, 0.32433627, 0.32433627, 0.32433627, 0.32433627,
        0.        , 0.32433627, 0.23076793, 0.        , 0.        ,
        0.        , 0.32433627, 0.        , 0.32433627, 0.32433627],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.34287126, 0.        , 0.24395573, 0.68574252, 0.34287126,
        0.34287126, 0.        , 0.34287126, 0.        , 0.        ]])

In [33]:
vec_dataframe = pd.DataFrame(result.toarray(), columns=vec.get_feature_names_out())
vec_dataframe

amazing        an    career   current      data      deep        in  \
0  0.324336  0.324336  0.324336  0.324336  0.324336  0.000000  0.324336   
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.342871  0.000000   

         is  learning   machine        of   science    subset       the  \
0  0.230768  0.000000  0.000000  0.000000  0.324336  0.000000  0.324336   
1  0.243956  0.685743  0.342871  0.342871  0.000000  0.342871  0.000000   

      world  
0  0.324336  
1  0.000000